attention_head_size: 1
categorical_groups: {}
causal_attention: true
dropout: 0.1
embedding_labels: {}
embedding_paddings: []
embedding_sizes: {}
hidden_continuous_size: 8
hidden_continuous_sizes: {}
hidden_size: 16
learning_rate: 0.03
log_gradient_flow: false
log_interval: 1
log_val_interval: 1
lstm_layers: 1
max_encoder_length: 7
monotone_constaints: {}
optimizer: ranger
optimizer_params: null
output_size:
- 1
- 1
- 1
output_transformer: !!python/object:pytorch_forecasting.data.encoders.MultiNormalizer
  fitted_: true
  normalizers:
  - !!python/object:pytorch_forecasting.data.encoders.GroupNormalizer
    center: true
    groups: &id002 []
    method: standard
    norm_:
      center: !!python/object/apply:numpy.core.multiarray.scalar
      - &id001 !!python/object/apply:numpy.dtype
        args:
        - f8
        - false
        - true
        state: !!python/tuple
        - 3
        - <
        - null
        - null
        - null
        - -1
        - -1
        - 0
      - !!binary |
        qP68ZU7+QEA=
      scale: !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        1XhN6RzJOkA=
    scale_by_group: false
    transformation: relu
  - !!python/object:pytorch_forecasting.data.encoders.GroupNormalizer
    center: true
    groups: *id002
    method: standard
    norm_:
      center: !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        U3iHeQFhV0A=
      scale: !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        NSQozPz3FEA=
    scale_by_group: false
    transformation: relu
  - !!python/object:pytorch_forecasting.data.encoders.GroupNormalizer
    center: true
    groups: *id002
    method: standard
    norm_:
      center: !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        hL7k7rcnJ0A=
      scale: !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        Dtajqs67HEA=
    scale_by_group: false
    transformation: null
reduce_on_plateau_min_lr: 1.0e-05
reduce_on_plateau_patience: 3
reduce_on_plateau_reduction: 2.0
share_single_variable_networks: false
static_categoricals: []
static_reals:
- week
- encoder_length
- target_duration_center
- target_duration_scale
- target_efficiency_center
- target_efficiency_scale
- target_start_hour_center
- target_start_hour_scale
time_varying_categoricals_decoder: []
time_varying_categoricals_encoder: []
time_varying_reals_decoder:
- time_idx
- week
- relative_time_idx
time_varying_reals_encoder:
- time_idx
- week
- relative_time_idx
- target_duration
- target_efficiency
- target_start_hour
- total_cycle_duration_minutes
- breaks_count
- avg_temperature
- avg_humidity
- avg_brightness
- avg_white_noise_level
weight_decay: 0.0
x_categoricals: []
x_reals:
- week
- encoder_length
- target_duration_center
- target_duration_scale
- target_efficiency_center
- target_efficiency_scale
- target_start_hour_center
- target_start_hour_scale
- time_idx
- week
- relative_time_idx
- target_duration
- target_efficiency
- target_start_hour
- total_cycle_duration_minutes
- breaks_count
- avg_temperature
- avg_humidity
- avg_brightness
- avg_white_noise_level
